disabled_rules: # rule identifiers turned on by default to exclude from running
  - line_length
  - identifier_name
  - function_body_length
  - type_body_length
  - force_cast
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
