name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_12.4.app
      
    - name: Install Dependencies
      run: |
         pod install --repo-update
      
    - name: Build and test
      run: |
        xcodebuild clean build test -workspace Primovie.xcworkspace -scheme "CI" -destination "platform=iOS Simulator,name=iPhone 11"
