name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2

    - name: Select Xcode
      run: sudo xcode-select --switch /Applications/Xcode_13.0.app/Contents/Developer
       
    - name: Install Dependencies
      run: pod install --repo-update
      shell: bash
      
    - name: Build and test
      run: xcodebuild clean build test -workspace 'Primovie.xcworkspace' -scheme CI -destination 'platform=iOS Simulator,name=iPhone 11'
